import matplotlib.colors as mcl

css4 = mcl.CSS4_COLORS
tableau = mcl.TABLEAU_COLORS
base = mcl.BASE_COLORS

COLORS = [
    base['b'],
    tableau['tab:orange'],
    base['g'],
    base['r'],
    base['c'],
    base['m'],
    base['y'],
    base['k'],
    tableau['tab:blue'],
    tableau['tab:green'],
    tableau['tab:red'],
    tableau['tab:purple'],
    tableau['tab:brown'],
    tableau['tab:pink'],
    tableau['tab:gray'],
    css4['brown'],
    css4['salmon'],
    css4['chocolate'],
    css4['burlywood'],
    css4['darkgoldenrod'],
    css4['gold'],
    css4['khaki'],
    css4['yellow'],
    css4['darkolivegreen'],
    css4['chartreuse'],
    css4['lime'],
    css4['turquoise'],
    css4['darkslategray'],
    css4['cadetblue'],
    css4['powderblue'],
    css4['steelblue'],
    css4['dodgerblue'],
    css4['royalblue'],
    css4['navy'],
    css4['mediumblue'],
    css4['slateblue'],
    css4['blueviolet'],
    css4['mediumorchid'],
    css4['darkmagenta'],
    css4['magenta'],
    css4['deeppink'],
    css4['palevioletred'],
          ]