dataset_creation: False
data_analysis: True

DATASET_CREATION:
  collect_episodes: False
  num_collect: 50000
  DATASET_CREATOR:
    algorithm: dqn
    environment: CartPole-v1
    save_dir: ./data_zoo
    load_path: NULL

DATA_ANALYSIS:
  dataset_path: ./data_zoo/dqn-CartPole-v1-50000.pkl
  EMBEDDINGS:
    load_embeddings: True
    num_components: 2
    perplexity: 30
    activation_key: latent_qs
  CLUSTERS:
    load_clusters: True
    num_clusters: 4
    temporal_discount: 0.25
    clustering_method: kgmeans
