[tool.poetry]
name = "arlin"
version = "0.1.0"
description = "Adversarial Reinforcement Learning for Model Interrogation"
authors = ["Alex Tapley <atapley@mitre.org>"]
readme = "README.md"
keywords = ["python", "reinforcement learning", "adversarial", "explainable"]
repository = "https://gitlab.mitre.org/ecrp/arlin"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
stable-baselines3 = "2.0.0"
huggingface-sb3 = "^2.2.4"
pyyaml = "^6.0"
tqdm = "^4.64.1"
scikit-learn = "^1.2.1"
swig = "^4.1.1"
box2d-py = "^2.3.8"
networkx = "^3.1"
ptable = "^0.9.2"
gymnasium = "^0.28.1"
tslearn = "^0.6.1"
gym = "^0.26.2"
shimmy = "^1.1.0"
